### ISSUE TITLE
ice: Vertical thermo error

### ISSUE THREAD

**Issue by PaulSpence** [OceansAus/01deg_jra55_ryf#2]
Sorry, but the 1/10th RYF isn't working for me. Getting error:

ice: Vertical thermo error

forrtl: error (78): process killed (SIGTERM)

Apparently this may be related to mushy ice? I have tried lowering the time step to 300,200 and 100 to get past the error but no luck. The model is at /home/561/pas561/payu/01deg_jra55v13_ryf8485_spinup7

It has only run for about 2 yrs.

**Comment by PaulSpence** [comment]
From Andrew Kiss:

Hi Paul

I resolved this previously by switching to mushy ice, but we don't want to do that as it slows CICE down by about 15%.

/home/561/pas561/payu/01deg_jra55v13_ryf8485_spinup7/work/ice/ice.log.task_0829
gives more details (see below)

crash is at  Lat, Lon:   63.4509502355987        21.8499999999952
this is in the Gulf of Bothnia
https://www.google.com.au/maps/place/63.4509502355987,21.8499999999952

I'm not sure what to suggest but here are some further details if that helps:

`Thermo iteration does not converge` comes from subroutine temperature_changes in ice_therm_bl99.F90
https://github.com/OceansAus/cice5/blob/39ecafdf4e487e9ae8ce7d6730b2e3919cf54635/source/ice_therm_bl99.F90#L865
This uses an iterative tridiagonal solver with `nitermax` iterations. 
The solution hasn't converged within allowed tolerances (see below) within `nitermax` iterations.
`nitermax=100` is hard-coded, not a namelist variable.
We could increase `nitermax` and recompile, but the CICE manual p57 says iteration usually converges within 4 iterations 
- so presumably things are going quite badly wrong it we get to 100

NB
- aice:  1.252300798563502E-009 is tiny
- Ice thickness:  1.000000000000000E-002 is very thin and presumably a default minimum value?
- Flux conservation error =   6.308680094018468E-002     

Convergence criteria from code:
```
!-----------------------------------------------------------------
! Determine whether the computation has converged to an acceptable
! solution.  Five conditions must be satisfied:
!
!    (1) Tsf <= 0 C.   - OK (just): Tsf=0.0
!    (2) Tsf is not oscillating; i.e., if both dTsf(niter) and
!        dTsf(niter-1) have magnitudes greater than puny, then
!        dTsf(niter)/dTsf(niter-1) cannot be a negative number
!        with magnitude greater than 0.5.  - seems OK
!    (3) abs(dTsf) < Tsf_errmax   - OK: dTsf = 0.0
!    (4) If Tsf = 0 C, then the downward turbulent/radiative 
!        flux, fsurfn, must be greater than or equal to the downward
!        conductive flux, fcondtopn.   - OK
!    (5) The net energy added to the ice per unit time must equal 
!        the net change in internal ice energy per unit time,
!        within the prescribed error ferrmax. - **FAILS**  ferrmax = 1.0e-3,  Flux conservation error =  6.308680094018468E-002
!
! For briny ice (the standard case), zTsn and zTin are limited
!  to prevent them from exceeding their melting temperatures.
!  (Note that the specific heat formula for briny ice assumes
!  that T < Tmlt.)  
! For fresh ice there is no limiting, since there are cases
!  when the only convergent solution has zTsn > 0 and/or zTin > 0.
!  Above-zero temperatures are then reset to zero (with melting 
!  to conserve energy) in the thickness_changes subroutine.
!-----------------------------------------------------------------  
```
```
Tsf_errmax = 5.e-4_dbl_kind ! max allowed error in Tsf
                            ! recommend Tsf_errmax < 0.01 K
```
seem small but is not the test that fails
```
ferrmax = 1.0e-3_dbl_kind    ! max allowed energy flux error (W m-2)
                             ! recommend ferrmax < 0.01 W m-2
```
Flux conservation error =   6.308680094018468E-002     (ferr)
so this is what fails
```
ferr(m) = abs( (enew(ij)-einit(m))/dt &
        - (fcondtopn(i,j) - fcondbot(m) + fswint(i,j)) )
```
```
fswint          ! SW absorbed in ice interior below surface (W m-2)
```
and this is zero, which is odd - maybe due to thinness of ice?


cheers
Andrew

**Comment by PaulSpence** [comment]
Hi Paul

I was hoping we'd dig into this a bit further and find a way to avoid mushy ice, as I'd really like to avoid it for the next IAF spinup... 

but if you insist, you can turn on mushy with these changes in ice/cice_in.nml:
ktherm            = 2
tfrz_option     = 'mushy'

If you take this route, please to first do
git commit -am "Final config with Bitz & Lipscomb (1999) ice thermodynamics"
then make the above edits to ice/cice_in.nml
then 
git commit -am "Use mushy ice thermodynamics (ktherm=2, tfrz_option='mushy'); this undoes commit 816fd0df"
so we have a clear record of when this change was made.

**Comment by PaulSpence** [comment]
Thanks for the info. I'll turn on mushy ice, see if we can get a few years, and then maybe turn it off to see if it will stabilize.

But do we need to restart from initial conditions to turn mushy ice on/off? i.e. do the existing restarts need different inputs? I'll try and see ...

**Comment by PaulSpence** [comment]
You can turn on mushy ice and continue from where you're at, however it might be impossible to return to non-mushy - I tried it and hit this same error so I was stuck with mushy and the long runtime it requires. 

So it is probably an irrevocable decision, which is why it would be nice to exhaust all other possibilities first.

Also do you have the headroom to sacrifice 15% and still get a 3mo run in 5hr walltime? See the attached. Note that run_summary_01deg_jra55v13_ryf8485_spinup6_newtopog_scalewind uses fewer cores.

**Comment by AndyHoggANU** [comment]
We've decided to go with mushy ice for our next long RYF spinup. We may still consider going back to ktherm=1 for future IAF runs.
