### ISSUE TITLE
Configuration for July 2019 RYF spinup

### ISSUE THREAD

**Issue by russfiedler** [OceansAus/01deg_jra55_ryf#4]
This is the spot for discussing issues related to the configuration of the RYF spinup to be commenced in July 2019.

The (initial) configuration can be found here.

https://github.com/COSIMA/01deg_jra55_ryf/tree/01deg_jra55v13_ryf9091/ocean

See @AndyHoggANU 's call for comments here:

https://arccss.slack.com/archives/C6PP0GU9Y/p1561332585035400

**Comment by russfiedler** [comment]
I think global integrals should really be saved in double precision. Some quantities, especially the 3D integrals, may vary by amounts which can't be detected at single precision or are not well resolved. There's no difference in the computational cost and the storage cost is miniscule.

In ocean_density_nml we have `neutralrho_max = 1030.0` and `neutralrho_min = 1020.0`. If we we using neutral density properly in MOM these values would be ok but this hasn't been implemented and we actually use `pot_rho_2000` instead which takes values that are much larger. You can see the problem in the output for `ty_trans_nrho_submeso` which hardly has any values.  Changing the range to be the same as `potrho` should be all that is needed.

https://github.com/COSIMA/01deg_jra55_ryf/blob/01deg_jra55v13_ryf9091/ocean/input.nml#L154-L157

**Comment by AndyHoggANU** [comment]
Thanks Russ - done both of these.

**Comment by russfiedler** [comment]
Is `debug_diag_manager = .true.` in `diag_manager_nml` really needed for production runs? It creates a hell of a lot of ASCII output that clutters up the log file.

https://github.com/COSIMA/01deg_jra55_ryf/blob/master/ocean/input.nml#L21

**Comment by russfiedler** [comment]
There are still restoring(?) field files with initial dates referencing the initial year as `0000` resulting in thousands of messages like

` WARNING from PE  1606: set_date_c: Year zero is invalid. Resetting year to 1`

This has been an issue for years and can be trivially fixed by setting the year to `0001`. I thought it had been but it still keeps coming back from the grave. Now is a good time to slay this zombie once and for all.

**Comment by AndyHoggANU** [comment]
Thanks @russfiedler - changed the `debug_diag_manager` to `.false.`
I would also like to eliminate those `set_date_c` warnings. It seems that it is the default `salt_sfc_restore.nc` which is the culprit:
```
	double time(time) ;
		time:long_name = "time" ;
		time:cartesian_axis = "T" ;
		time:axis = "T" ;
		time:calendar_type = "noleap" ;
		time:calendar = "noleap" ;
		time:modulo = " " ;
		time:standard_name = "time" ;
		time:units = "months since 0000-01-01 00:00:00" ;
		time:climatology = "climatology_bounds" ;
...
 time = 0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5, 11.5 ;
```
@aidanheerdegen  - any chance you could have a quick look at this tomorrow? Would be great to change the time units, or if that wasn't possible add a year to the time vector. Let me know what you think.

**Comment by russfiedler** [comment]
The thing that needs to be done is is change the year to `0001`. Changing the units won't affect the messages but having unit of months is pretty nasty.

**Comment by aidanheerdegen** [comment]
New version here

`/short/public/aph502/salt_sfc_restore.nc`

but I don't have write permissions in `/short/public/access-om2/input_08022019/mom_01deg`. @aekiss can you copy the modified file over . You don't need to worry about overwriting that file, there are a bunch of copies:
```
$ find . -name salt_sfc_restore.nc | grep mom_01deg | xargs md5sum
441cd4ed3336f5d8567dedf55b993160  ./input_2f3648a7/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_2407a7bc/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_b72797e1/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_a3373a31/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_236a3011/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_46fb3d3b/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_337f4505/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_ff9890e2/mom_01deg/salt_sfc_restore.nc
2971a5aac20ffd58e2b3096991ba5ee1  ./input_rc/mom_01deg/salt_sfc_restore.nc
2971a5aac20ffd58e2b3096991ba5ee1  ./input_08022019/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_eee21b65/mom_01deg/salt_sfc_restore.nc
441cd4ed3336f5d8567dedf55b993160  ./input_38570c62/mom_01deg/salt_sfc_restore.nc
```
which is in itself something to address:
```
$ find . -path  "*mom_01deg/salt_sfc_restore.nc" -exec du -shc {} +
446M    ./input_2f3648a7/mom_01deg/salt_sfc_restore.nc
446M    ./input_2407a7bc/mom_01deg/salt_sfc_restore.nc
446M    ./input_b72797e1/mom_01deg/salt_sfc_restore.nc
446M    ./input_a3373a31/mom_01deg/salt_sfc_restore.nc
446M    ./input_236a3011/mom_01deg/salt_sfc_restore.nc
446M    ./input_46fb3d3b/mom_01deg/salt_sfc_restore.nc
446M    ./input_337f4505/mom_01deg/salt_sfc_restore.nc
446M    ./input_ff9890e2/mom_01deg/salt_sfc_restore.nc
446M    ./input_rc/mom_01deg/salt_sfc_restore.nc
446M    ./input_08022019/mom_01deg/salt_sfc_restore.nc
446M    ./input_eee21b65/mom_01deg/salt_sfc_restore.nc
446M    ./input_38570c62/mom_01deg/salt_sfc_restore.nc
5.3G    total
```

**Comment by aekiss** [comment]
OK I've just copied `/short/public/aph502/salt_sfc_restore.nc` to `/short/public/access-om2/input_08022019/mom_01deg`
